services:
  - type: web
    name: image-to-video-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT images_to_video_converter_with_songs.app:app
    plan: free